services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    container_name: whatsapp
    restart: always
    ports:
      - "3500:3000"
    volumes:
      - whatsapp:/app/storages
    environment:
      WHATSAPP_WEBHOOK: https://webhook.site/56daebcf-0ea3-400f-8bb5-de98580c62ae
    command:
      - rest
      #- --basic-auth=admin:admin
      - --port=3000
      - --debug=false
      - --os=NS-Zap
      - --account-validation=false
      - --webhook="https://webhook.site/56daebcf-0ea3-400f-8bb5-de98580c62ae"

volumes:
  whatsapp: