services:
  whatsapp:
    build:
      context: .
      dockerfile: docker/golang.Dockerfile
    container_name: whatsapp-local
    restart: always
    ports:
      - "3500:3000"
    volumes:
      - whatsapp:/app/storages
      - ./src/statics:/app/statics
    environment:
      WHATSAPP_WEBHOOK: https://webhook.site/81ff43c2-547b-4c8b-8ad1-f9d503621faa
    command:
      - rest
      #- --basic-auth=admin:admin
      - --port=3000
      - --debug=false
      - --os=NS-Zap
      - --account-validation=false
      - --webhook="https://webhook.site/81ff43c2-547b-4c8b-8ad1-f9d503621faa"

volumes:
  whatsapp: 